// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0LuigiCode0/tshort/example (interfaces: Doo)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/mock.go -package=mocks . Doo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	test1 "github.com/0LuigiCode0/tshort/example/test1"
	gomock "go.uber.org/mock/gomock"
)

// MockDoo is a mock of Doo interface.
type MockDoo struct {
	ctrl     *gomock.Controller
	recorder *MockDooMockRecorder
	isgomock struct{}
}

// MockDooMockRecorder is the mock recorder for MockDoo.
type MockDooMockRecorder struct {
	mock *MockDoo
}

// NewMockDoo creates a new mock instance.
func NewMockDoo(ctrl *gomock.Controller) *MockDoo {
	mock := &MockDoo{ctrl: ctrl}
	mock.recorder = &MockDooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoo) EXPECT() *MockDooMockRecorder {
	return m.recorder
}

// A mocks base method.
func (m *MockDoo) A(arg0 *int, arg1 int, arg2 []byte) (test1.INT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "A", arg0, arg1, arg2)
	ret0, _ := ret[0].(test1.INT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// A indicates an expected call of A.
func (mr *MockDooMockRecorder) A(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "A", reflect.TypeOf((*MockDoo)(nil).A), arg0, arg1, arg2)
}

// B mocks base method.
func (m *MockDoo) B() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "B")
}

// B indicates an expected call of B.
func (mr *MockDooMockRecorder) B() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "B", reflect.TypeOf((*MockDoo)(nil).B))
}
